receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318

processors:
  batch:

      
exporters:
  azuremonitor:
    connection_string: ""  # copy from Azure Application Insights instance
 
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
